"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var fabricaAnimales_1 = require("./fabricaAnimales");
//let perro = new Perro("Ayudante de Santa", "Galgo", "Marron");
//let gato = new Gato("Bola de Nieve", "Callejero", "Negro");
//let pajaro = new Pajaro("Twitty", "Canario", "Amarillo");
var fabrica = new fabricaAnimales_1.FabricaDeAnimales();
var nuevoGato = fabrica.crearAnimales("gato", "Bola de Nieve", "Callejero", "Negro");
var nuevoPerro = fabrica.crearAnimales("perro", "Ayudante de Santa", "Galgo", "Marron");
var nuevoPajaro = fabrica.crearAnimales("pajaro", "Twitty", "Canario", "Amarillo");
console.log(nuevoGato);
nuevoGato.hacerSonido();
nuevoGato.mover();
console.log("---------------------------------------------------------------------------");
console.log(nuevoPerro);
nuevoPerro.hacerSonido();
nuevoPerro.mover();
console.log("---------------------------------------------------------------------------");
console.log(nuevoPajaro);
nuevoPajaro.hacerSonido();
nuevoPajaro.mover();
